openapi: 3.0.0
info:
  title: Ecomm
  contact: {}
  version: '1.0'
servers:
- url: http://https://ecommerce-api-pm9q.onrender.com/api/v1
  variables: {}
paths:
  /auth/logout:
    get:
      tags:
      - auth
      summary: logout
      operationId: logout
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /auth/login:
    post:
      tags:
      - auth
      summary: login
      operationId: login
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/loginrequest'
              - example:
                  email: peter@gmail.com
                  password: peter123
            example:
              email: peter@gmail.com
              password: peter123
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /auth/register:
    post:
      tags:
      - auth
      summary: register
      operationId: register
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/registerrequest'
              - example:
                  name: Ajaya
                  email: ajaya@gmail.com
                  password: ajaya123
            example:
              name: Ajaya
              email: ajaya@gmail.com
              password: ajaya123
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /users:
    get:
      tags:
      - users
      summary: Get all users
      operationId: Getallusers
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /users/63cf1563ec7d12054fcf95c2:
    get:
      tags:
      - users
      summary: Get single User
      operationId: GetsingleUser
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /users/showMe:
    get:
      tags:
      - users
      summary: Show Current User
      operationId: ShowCurrentUser
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /users/updateUser:
    patch:
      tags:
      - users
      summary: Update User
      operationId: UpdateUser
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/UpdateUserRequest'
              - example:
                  name: newAjaya
                  email: ajaya@gmail.com
            example:
              name: newAjaya
              email: ajaya@gmail.com
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /users/updateUserPassword:
    patch:
      tags:
      - users
      summary: updateUserPassword
      operationId: updateUserPassword
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/updateUserPasswordRequest'
              - example:
                  oldPassword: ajaya123
                  newPassword: newAjaya123
            example:
              oldPassword: ajaya123
              newPassword: newAjaya123
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /products:
    get:
      tags:
      - Products
      summary: Get all products
      operationId: Getallproducts
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    post:
      tags:
      - Products
      summary: Create Product
      operationId: CreateProduct
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/CreateProductRequest'
              - example:
                  name: This is prduct 2
                  price: 500
                  image: https://dl.airtable.com/.attachmentThumbnails/e8bc3791196535af65f40e36993b9e1f/438bd160
                  colors:
                  - '#00ff00'
                  - '#0000ff'
                  company: ikea
                  description: Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge
                  category: office
            example:
              name: This is prduct 2
              price: 500
              image: https://dl.airtable.com/.attachmentThumbnails/e8bc3791196535af65f40e36993b9e1f/438bd160
              colors:
              - '#00ff00'
              - '#0000ff'
              company: ikea
              description: Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge
              category: office
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /products/63cde68616b91361adcc8f2a:
    get:
      tags:
      - Products
      summary: Get single product
      operationId: Getsingleproduct
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /products/63cf1707ec7d12054fcf95d8:
    patch:
      tags:
      - Products
      summary: Update Products
      operationId: UpdateProducts
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/UpdateProductsRequest'
              - example:
                  name: This is prduct 2
                  price: 6500
                  image: https://dl.airtable.com/.attachmentThumbnails/e8bc3791196535af65f40e36993b9e1f/438bd160
                  colors:
                  - '#00ff00'
                  - '#0000ff'
                  company: ikea
                  description: Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge
                  category: office
            example:
              name: This is prduct 2
              price: 6500
              image: https://dl.airtable.com/.attachmentThumbnails/e8bc3791196535af65f40e36993b9e1f/438bd160
              colors:
              - '#00ff00'
              - '#0000ff'
              company: ikea
              description: Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge
              category: office
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /products/63ccbc56109312759270cfb2:
    delete:
      tags:
      - Products
      summary: Delete Products
      operationId: DeleteProducts
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /products/uploadImage:
    post:
      tags:
      - Products
      summary: Upload Image
      operationId: UploadImage
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /reviews:
    get:
      tags:
      - Products
      summary: Get all reviews
      operationId: Getallreviews
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    post:
      tags:
      - Products
      summary: Create Review
      operationId: CreateReview
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/CreateReviewRequest'
              - example:
                  rating: '4'
                  title: This is the second review
                  comment: It is the best product ever
                  product: 63cf1707ec7d12054fcf95d8
            example:
              rating: '4'
              title: This is the second review
              comment: It is the best product ever
              product: 63cf1707ec7d12054fcf95d8
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /products/63ccbc56109312759270cfb2/reviews:
    get:
      tags:
      - Products
      summary: Get single product review
      operationId: Getsingleproductreview
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /reviews/63cf1879ec7d12054fcf95e8:
    get:
      tags:
      - Reviews
      summary: Get single review
      operationId: Getsinglereview
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    patch:
      tags:
      - Reviews
      summary: Update Review
      operationId: UpdateReview
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/UpdateReviewRequest'
              - example:
                  rating: 4
                  title: Best Product
                  comment: Updated my review
                  product: 63cde68616b91361adcc8f2a
            example:
              rating: 4
              title: Best Product
              comment: Updated my review
              product: 63cde68616b91361adcc8f2a
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /reviews/63cde6c916b91361adcc8f30:
    delete:
      tags:
      - Reviews
      summary: Delete Review
      operationId: DeleteReview
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
components:
  schemas:
    loginrequest:
      title: loginrequest
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: peter@gmail.com
        password: peter123
    registerrequest:
      title: registerrequest
      required:
      - name
      - email
      - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      example:
        name: Ajaya
        email: ajaya@gmail.com
        password: ajaya123
    UpdateUserRequest:
      title: UpdateUserRequest
      required:
      - name
      - email
      type: object
      properties:
        name:
          type: string
        email:
          type: string
      example:
        name: newAjaya
        email: ajaya@gmail.com
    updateUserPasswordRequest:
      title: updateUserPasswordRequest
      required:
      - oldPassword
      - newPassword
      type: object
      properties:
        oldPassword:
          type: string
        newPassword:
          type: string
      example:
        oldPassword: ajaya123
        newPassword: newAjaya123
    CreateProductRequest:
      title: CreateProductRequest
      required:
      - name
      - price
      - image
      - colors
      - company
      - description
      - category
      type: object
      properties:
        name:
          type: string
        price:
          type: integer
          format: int32
        image:
          type: string
        colors:
          type: array
          items:
            type: string
          description: ''
        company:
          type: string
        description:
          type: string
        category:
          type: string
      example:
        name: This is prduct 2
        price: 500
        image: https://dl.airtable.com/.attachmentThumbnails/e8bc3791196535af65f40e36993b9e1f/438bd160
        colors:
        - '#00ff00'
        - '#0000ff'
        company: ikea
        description: Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge
        category: office
    UpdateProductsRequest:
      title: UpdateProductsRequest
      required:
      - name
      - price
      - image
      - colors
      - company
      - description
      - category
      type: object
      properties:
        name:
          type: string
        price:
          type: integer
          format: int32
        image:
          type: string
        colors:
          type: array
          items:
            type: string
          description: ''
        company:
          type: string
        description:
          type: string
        category:
          type: string
      example:
        name: This is prduct 2
        price: 6500
        image: https://dl.airtable.com/.attachmentThumbnails/e8bc3791196535af65f40e36993b9e1f/438bd160
        colors:
        - '#00ff00'
        - '#0000ff'
        company: ikea
        description: Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge
        category: office
    CreateReviewRequest:
      title: CreateReviewRequest
      required:
      - rating
      - title
      - comment
      - product
      type: object
      properties:
        rating:
          type: string
        title:
          type: string
        comment:
          type: string
        product:
          type: string
      example:
        rating: '4'
        title: This is the second review
        comment: It is the best product ever
        product: 63cf1707ec7d12054fcf95d8
    CreateReviewRequest1:
      title: CreateReviewRequest1
      required:
      - rating
      - title
      - comment
      - product
      type: object
      properties:
        rating:
          type: integer
          format: int32
        title:
          type: string
        comment:
          type: string
        product:
          type: string
      example:
        rating: 4
        title: Average Product
        comment: It is the best product i ever had
        product: 63cde68616b91361adcc8f2a
    UpdateReviewRequest:
      title: UpdateReviewRequest
      required:
      - rating
      - title
      - comment
      - product
      type: object
      properties:
        rating:
          type: integer
          format: int32
        title:
          type: string
        comment:
          type: string
        product:
          type: string
      example:
        rating: 4
        title: Best Product
        comment: Updated my review
        product: 63cde68616b91361adcc8f2a
tags:
- name: auth
- name: users
- name: Products
- name: Reviews